VERSION=1.0.0
PACKAGE=vnc-history-zimlet
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=base
ARCHITECTURE=All
PRIORITY=optional
DEPENDS=zcs-core-libs,zcs-lib-vnc-common,zcs-lib-json-simple
DESCRIPTION=Ligthweight history zimlet to get history of mail.
REDMINE_UPLOAD_PROJECT=history-zimlet-to-gallery
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
LICENSE=Proprietary
