TOPDIR=../../
JAR_FILE_NAME=zcs-lib-vnc-lightweight-history.jar

ZCS_LIB_JARS=\
	zcs-lib-vnc-common.jar		\
	zcs-lib-json-simple.jar		\
	servlet-api.jar			\
	zimbrastore.jar			\
	zimbracommon.jar

INSTALL_USER=y
INSTALL_ADMIN=y
INSTALL_SERVICE=y
INSTALL_EXTENSION=y
INSTALL_ZIMLET=y

include $(TOPDIR)/common.mk
include $(ZIMBRA_BUILD_ROOT)/extensions-extra/zmpkg/mk/zcs-java-lib.mk
