
ZIMLET_NAME=biz_vnc_lightweight_history


TOPDIR=../..

ZCS_LIB_JARS=\
	../lib-vnc-lightweight-history/zcs-lib-vnc-lightweight-history.jar \
	zcs-lib-vnc-common.jar \
	zcs-lib-json-simple.jar \
	zcs-lib-vnc-pro.jar	\
	zimbrastore.jar \
    zimbracommon.jar	



include $(TOPDIR)/common.mk
include $(ZIMBRA_BUILD_ROOT)/extensions-extra/zmpkg/mk/zcs-zimlet.mk
